Configure GitHub Actions

diff --git a/.github/workflows/build-releases.yml b/.github/workflows/build-releases.yml
--- a/.github/workflows/build-releases.yml
+++ b/.github/workflows/build-releases.yml
@@ -1,46 +1,56 @@
 name: Build container release images
 on:
-  push:
-    tags:
-      - '*'
-
-permissions:
-  contents: read
-  packages: write
+  workflow_dispatch:
 
 jobs:
+  compute-variant:
+    runs-on: ubuntu-latest
+    steps:
+      - id: variant_vars
+        run: |
+          # extract variant from branch name (e.g. odakyudon, nitiasadon)
+          variant=${GITHUB_REF#refs/heads/*/}
+          # verify that the variant is one of the expected ones
+          if [[ "$variant" != "odakyudon" && "$variant" != "nitiasadon" ]]; then
+            echo "Error: Unexpected variant '$variant'" >&2
+            exit 1
+          fi
+          echo mastodon_variant=$variant >> $GITHUB_OUTPUT
+    outputs:
+      variant: ${{ steps.variant_vars.outputs.mastodon_variant }}
+
   build-image:
+    needs: compute-variant
     uses: ./.github/workflows/build-container-image.yml
     with:
       file_to_build: Dockerfile
       push_to_images: |
-        tootsuite/mastodon
-        ghcr.io/mastodon/mastodon
+        accelforce/${{ needs.compute-variant.outputs.variant }}
       # Do not use cache when building releases, so apt update is always ran and the release always contain the latest packages
       cache: false
       # Only tag with latest when ran against the latest stable branch
       # This needs to be updated after each minor version release
       flavor: |
-        latest=${{ startsWith(github.ref, 'refs/tags/v4.4.') }}
+        latest=auto
       tags: |
-        type=pep440,pattern={{raw}}
-        type=pep440,pattern=v{{major}}.{{minor}}
+        type=raw,value=latest
+        type=sha,prefix=
     secrets: inherit
 
   build-image-streaming:
+    needs: compute-variant
     uses: ./.github/workflows/build-container-image.yml
     with:
       file_to_build: streaming/Dockerfile
       push_to_images: |
-        tootsuite/mastodon-streaming
-        ghcr.io/mastodon/mastodon-streaming
+        accelforce/${{ needs.compute-variant.outputs.variant }}-streaming
       # Do not use cache when building releases, so apt update is always ran and the release always contain the latest packages
       cache: false
       # Only tag with latest when ran against the latest stable branch
       # This needs to be updated after each minor version release
       flavor: |
-        latest=${{ startsWith(github.ref, 'refs/tags/v4.4.') }}
+        latest=auto
       tags: |
-        type=pep440,pattern={{raw}}
-        type=pep440,pattern=v{{major}}.{{minor}}
+        type=raw,value=latest
+        type=sha,prefix=
     secrets: inherit
